name: code_postaux
description: Search french city name and INSEE code by zip code.
version: 1.0.2
author: Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Kleak/code_postaux

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
 http: ">=1.1.0 <=1.1.0"

dev_dependencies:
  test: '>=1.24.0 <=1.24.6'
